apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  labels:
    app.podman.io/name: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch
  labels:
    app.podman.io/name: elasticsearch
stringData:
  ELASTIC_PASSWORD: password

---

apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app.podman.io/name: elasticsearch
spec:
  containers:
    - name: elasticsearch
      image: docker.io/library/elasticsearch:8.14.3
      env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_USERNAME
          value: elastic
        - name: xpack.security.enabled
          value: 'true'
      envFrom:
        - secretRef:
            name: elasticsearch
      ports:
        - containerPort: 9200
          hostPort: 9200
        - containerPort: 9300
          hostPort: 9300
      resources:
        limits:
          memory: 2G
      volumeMounts:
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
  volumes:
    - name: elasticsearch
      persistentVolumeClaim:
        claimName: elasticsearch