apiVersion: v1
kind: Pod
metadata:
  name: it-tools
  labels:
    app.podman.io/name: it-tools
spec:
  containers:
    - name: it-tools
      image: docker.io/corentinth/it-tools
      ports:
        - containerPort: 80
          hostPort: 8080
