apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  labels:
    app.podman.io/name: mongo
spec:
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app.podman.io/name: mongo
stringData:
  MONGO_INITDB_ROOT_PASSWORD: password

---

apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app.podman.io/name: mongo
spec:
  containers:
    - name: mongo
      image: docker.io/library/mongo:7.0
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
      envFrom:
        - secretRef:
            name: mongo
      ports:
        - containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - name: mongo
          mountPath: /data/db
  volumes:
    - name: mongo
      persistentVolumeClaim:
        claimName: mongo